languageCode = "es"
languageName = "Español"
weight = 1
title = "S3ntinl"
contentDir = "content/pt"

[params]
displayName = "Español"
isoCode = "es"
rtl = false
description = "S3ntinl's Hacking Blog"
dateFormat = "02 / 01 / 2006"
author = { name = "S3ntinl", image = "img/author.jpeg", headline = "Ethical Hacker | Penetration Tester | Bug Bounty Hunter", bio = "Embrace The Unseen", links = [ { link = "https://app.hackthebox.com/profile/1650462" }, { github = "https://github.com/S3ntinl" }, { linkedin = "https://www.linkedin.com/in/marcosgarciaarcos/" } ] }

